# Generated by Django 5.1.5 on 2025-02-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='security_answer',
            new_name='maiden_name',
        ),
    ]
