# Generated by Django 5.1.6 on 2025-02-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_youtube_id',
            field=models.CharField(default='G7L4YzGAvMA', max_length=11),
            preserve_default=False,
        ),
    ]
